stages:
  - test_python

test_python_package:
  image: python:3.6
  stage: test_python

  tags:
    - docker

  before_script:
    - python -V
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install -e .

  script:
    - python setup.py test

  after_script:
    - rm -rf *.egg-info .eggs venv
