version: 2


variables:
  update_conda: &update_conda
    run:
      name: Update conda
      command: |
        conda update --yes conda
        conda update setuptools
  install_mmsplice: &install_mmsplice
    run:
      name: Install mmsplice
      command: pip install -e '.'
  install_dependencies: &install_dependencies
    run:
      name: Install dependencies not in miniconda3
      command: |
        apt-get update && \
        apt-get install -y build-essential libz-dev libcurl3-dev
        pip install concise
        pip install cython
  install_tensorflow1_11: &install_tensorflow1_11
    run:
      name: Install tensorflow 1.11
      command: pip install tensorflow==1.11
  install_tensorflow1_9: &install_tensorflow1_9
    run:
      name: Install tensorflow 1.9
      command: pip install tensorflow==1.9
  test_cli: &test_cli
    run:
      name: Test cli
      command: mmsplice
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        python setup.py test
  build_docker: &build_docker
    run:
      name: Build docker container
      command: |
        docker build -t mmsplice .
  test_docker: &test_docker
    run:
      name: Test vep plugin in docker
      command: |
        docker run -t -i mmsplice vep -i examples/drosophila_melanogaster_BDGP6.vcf --plugin MMSplice --database -o STDOUT

jobs:

  build:
    docker:
    - image: continuumio/miniconda3:4.3.14
    working_directory: ~/repo
    steps:
    - checkout
    - *update_conda
    - *install_dependencies
    - *install_tensorflow1_11
    - *install_mmsplice
    - *test_cli
    - *run_tests

  docker_testing:
    machine: true
    steps:
    - checkout
    - *build_docker
    - *test_docker

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - docker_testing
